-- WARNING: This will delete all existing data in 'tugas' table.
DROP TABLE IF EXISTS tugas CASCADE;

CREATE TABLE tugas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  peralatan_id BIGINT REFERENCES peralatan(id) ON DELETE SET NULL,
  judul VARCHAR(255),
  deskripsi TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROSES', 'SELESAI')),
  sumber VARCHAR(50) DEFAULT 'KANIT',
  
  dibuat_oleh_nip VARCHAR(50), 
  ditugaskan_ke_nip VARCHAR(50), 
  
  dibuat_kapan TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  diupdate_kapan TIMESTAMP WITH TIME ZONE,
  
  -- Constraints
  CONSTRAINT fk_tugas_pembuat FOREIGN KEY (dibuat_oleh_nip) REFERENCES akun(nip) ON UPDATE CASCADE ON DELETE SET NULL,
  CONSTRAINT fk_tugas_teknisi FOREIGN KEY (ditugaskan_ke_nip) REFERENCES akun(nip) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX idx_tugas_ditugaskan_ke ON tugas(ditugaskan_ke_nip);
CREATE INDEX idx_tugas_status ON tugas(status);
